# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0002_auto_20161009_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researcher', to=settings.AUTH_USER_MODEL),
        ),
    ]
