# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0002_auto_20161204_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='scientific_degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
