# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import projects.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=projects.utils.generate_uid, max_length=8, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
