# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('unique_id', models.CharField(default=projects.models.create_unique_id, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
