# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('protocols', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='protocols.Protocol'),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='protocols',
            field=models.ManyToManyField(related_name='projects', to='protocols.Protocol'),
        ),
        migrations.AddField(
            model_name='project',
            name='sources',
            field=models.ManyToManyField(related_name='projects', to='projects.Source'),
        ),
    ]
