# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocols', '0001_initial'),
        ('projects', '0001_initial'),
        ('researchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='protocols',
            field=models.ManyToManyField(blank=True, related_name='projects', to='protocols.Protocol'),
        ),
        migrations.AddField(
            model_name='project',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='projects', to='researchers.Source'),
        ),
    ]
