# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20161001_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='protocols',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='protocols.Protocol'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sources',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='projects.Source'),
        ),
        migrations.AlterField(
            model_name='role',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='role',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='protocols.Protocol'),
        ),
    ]
