# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20161009_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='protocols',
            field=models.ManyToManyField(blank=True, related_name='projects', to='protocols.Protocol'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Source'),
        ),
    ]
