# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researchers', '0001_initial'),
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='researchers.Researcher'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='assets',
            field=models.ManyToManyField(related_name='protocols', to='protocols.Asset'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='procedure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protocol', to='protocols.Procedure'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='protocols', to='researchers.Source'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='last_modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='researchers.Researcher'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachemnts', to='protocols.Result'),
        ),
    ]
