# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researchers', '0001_initial'),
        ('protocols', '0001_initial'),
        ('projects', '0002_auto_20161228_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='researchers.Researcher'),
        ),
        migrations.AddField(
            model_name='result',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='result',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='protocols.Protocol'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='protocols', to='protocols.Asset'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='protocols', to='researchers.Source'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='last_modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='researchers.Researcher'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='protocol',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='protocols.Protocol'),
        ),
        migrations.AddField(
            model_name='datacolumn',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_columns', to='protocols.Result'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachemnts', to='protocols.Result'),
        ),
    ]
