# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='procedure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protocol', to='protocols.Procedure'),
        ),
    ]
