# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_auto_20170531_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='data_type',
            new_name='data_type_dependent',
        ),
        migrations.AddField(
            model_name='result',
            name='data_type_independent',
            field=models.CharField(choices=[('number', 'Number'), ('string', 'Text'), ('boolean', 'Yes/No')], default='number', max_length=20),
        ),
    ]
