# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_datetime_created'),
        ('protocols', '0002_auto_20161031_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='name',
            new_name='text',
        ),
        migrations.AddField(
            model_name='datacolumn',
            name='result',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='data_columns', to='protocols.Result'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='result',
            name='protocol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='protocols.Protocol'),
            preserve_default=False,
        ),
    ]
