# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_auto_20161006_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='label',
            field=models.CharField(choices=[('standard', 'Standard'), ('modified', 'Modified')], max_length=20),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sources',
            field=models.ManyToManyField(blank=True, null=True, related_name='protocols', to='projects.Source'),
        ),
    ]
