# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0003_auto_20170518_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacolumn',
            options={'ordering': ['order']},
        ),
    ]
