# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0003_auto_20170607_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
