# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0003_auto_20161125_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('material', 'Material'), ('equipment', 'Equipment')], max_length=20),
        ),
    ]
