# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0004_auto_20161126_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='assets',
            field=models.ManyToManyField(blank=True, null=True, related_name='protocols', to='protocols.Asset'),
        ),
    ]
