# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0004_auto_20170320_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='label',
            field=models.CharField(choices=[('standard', 'Standard'), ('modified', 'Modified')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='step',
            name='text',
            field=models.TextField(max_length=1024),
        ),
    ]
