# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 15:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


data_columns = {
    "data_columns": [
        {
            "data": [0, 2, 4, 6, 8],
            "data_type": "independent_variable",
            "title": "Independent Variable"
        },
        {
            "data": [5, 4, 3, 2, 1],
            "title": "Trial 1",
            "data_type": "dependent_variable"
        },
        {
            "data": [5, 4, 3, 2, 1],
            "title": "Trial 2",
            "data_type": "dependent_variable"
        }
    ]
}


class Migration(migrations.Migration):
    dependencies = [
        ('protocols', '0004_auto_20170528_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacolumn',
            name='result',
        ),
        migrations.AddField(
            model_name='result',
            name='data_columns',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=data_columns),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='dependent_variable',
            field=models.CharField(default='Not Provided', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='independent_variable',
            field=models.CharField(default='Not Provided', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='title',
            field=models.CharField(default='Not Provided', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DataColumn',
        ),
    ]
