# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion

procedure = {
    "steps": [
        {
            "description": "Step 1 description",
            "title": "Step 1"
        },
        {
            "description": "Step 2 description",
            "title": "Step 2"
        },
        {
            "description": "Step 3 description",
            "title": "Step 3"
        },
        {
            "description": "Step 4 description",
            "title": "Step 4"
        },
        {
            "description": "Step 5 description",
            "title": "Step 5"
        },
        {
            "description": "Step 6 description",
            "title": "Step 6"
        },
        {
            "description": "Step 7 description",
            "title": "Step 7"
        },
    ]
}


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
        ('protocols', '0005_auto_20170529_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='step',
            name='procedure',
        ),
        migrations.AddField(
            model_name='protocol',
            name='datetime_last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='last_modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='researchers.Researcher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocol',
            name='procedure',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=procedure),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
