# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0005_auto_20170320_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='description',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.CharField(blank=True, default='default_title', max_length=255),
            preserve_default=False,
        ),
    ]
