# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0005_auto_20161126_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='procedure',
        ),
        migrations.AddField(
            model_name='procedure',
            name='protocol',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='protocols.Protocol'),
            preserve_default=False,
        ),
    ]
