# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0006_auto_20170328_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={},
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
