# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import protocols.utils


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0007_auto_20170412_0728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='result',
            name='unique_id',
            field=models.CharField(default=protocols.utils.generate_uid, max_length=8, unique=True),
        ),
    ]
