# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0008_auto_20170427_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacolumn',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
