# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0009_datacolumn_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacolumn',
            name='is_independent',
        ),
    ]
