# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0010_remove_datacolumn_is_independent'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacolumn',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
