# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import invitations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researchers', '0003_auto_20161204_1009'),
        ('projects', '0003_project_datetime_created'),
        ('protocols', '0009_auto_20161204_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('key', models.CharField(default=invitations.models.generate_key, editable=False, max_length=64, unique=True)),
                ('expiration_days', models.PositiveSmallIntegerField(default=3)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('invited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_invitations', to='researchers.Researcher')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_invitations', to='researchers.Researcher')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.Project')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='protocols.Protocol')),
            ],
        ),
    ]
