# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researchers', '0001_initial'),
        ('projects', '0001_initial'),
        ('invitations', '0001_initial'),
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_invitations', to='researchers.Researcher'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_invitations', to='researchers.Researcher'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='protocols.Protocol'),
        ),
    ]
