# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_auto_20170531_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['-datetime_created']},
        ),
    ]
