# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_auto_20170107_1330'),
        ('projects', '0002_auto_20170107_1330'),
        ('invitations', '0002_auto_20170107_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set([('email', 'project'), ('email', 'protocol')]),
        ),
    ]
