# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_auto_20170116_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('contributor', 'Contributor'), ('watcher', 'Watcher')], default='watcher', max_length=255),
        ),
    ]
